import{a as f,S as w,i as n}from"./assets/vendor-xJi9366P.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const v="55034335-d102dc4a43f72748c32c038be";f.defaults.baseURL="https://pixabay.com/api/";async function m(r,e){return(await f.get("",{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}const S=document.querySelector(".gallery"),y=document.querySelector(".loader"),g=document.querySelector(".load-more-btn");let q=new w(".gallery a",{captionsData:"alt",captionDelay:250});function p(r){const e=document.querySelector(".gallery"),a=r.map(s=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${s.largeImageURL}">
            <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}" />
          </a>
          <div class="info">
            <p><b>Likes</b> ${s.likes}</p>
            <p><b>Views</b> ${s.views}</p>
            <p><b>Comments</b> ${s.comments}</p>
            <p><b>Downloads</b> ${s.downloads}</p>
          </div>
        </li>
        `).join("");e.insertAdjacentHTML("beforeend",a),q.refresh()}function $(){S.innerHTML=""}function h(){y.classList.remove("is-hidden")}function b(){y.classList.add("is-hidden")}function L(){g.classList.remove("is-hidden")}function d(){g.classList.add("is-hidden")}const B=document.querySelector(".form"),M=document.querySelector(".load-more-btn");let l="",i=1,u=0;B.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.currentTarget.elements["search-text"].value.trim(),!l){n.warning({message:"Please enter a search query"});return}i=1,$(),d(),h();try{const e=await m(l,i);u=e.totalHits,e.hits.length===0?n.error({message:"Sorry, no images found!"}):(p(e.hits),u>15&&L()),r.target.reset()}catch(e){console.log(e),n.error({message:"Something went wrong!"})}finally{b()}});M.addEventListener("click",async()=>{i+=1,d(),h();try{const r=await m(l,i);p(r.hits);const e=document.querySelector(".gallery-item");if(e){const a=e.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}i*15>=u?(d(),n.info({message:"We're sorry, but you've reached the end of search results."})):L()}catch{n.error({message:"Error loading more images!"})}finally{b()}});
//# sourceMappingURL=index.js.map
