import{a as m,S as v,i as a}from"./assets/vendor-xJi9366P.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))f(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&f(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function f(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const S="55034335-d102dc4a43f72748c32c038be";m.defaults.baseURL="https://pixabay.com/api/";async function y(o,e){return(await m.get("",{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}const g=document.querySelector(".gallery"),h=document.querySelector(".loader"),p=document.querySelector(".load-more-btn");let q=new v(".gallery a",{captionsData:"alt",captionDelay:250});function b(o){const e=o.map(r=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${r.largeImageURL}">
            <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
          </a>
          <div class="info">
            <p><b>Likes</b> ${r.likes}</p>
            <p><b>Views</b> ${r.views}</p>
            <p><b>Comments</b> ${r.comments}</p>
            <p><b>Downloads</b> ${r.downloads}</p>
          </div>
        </li>
        `).join("");g.insertAdjacentHTML("beforeend",e),q.refresh()}function $(){g.innerHTML=""}function L(){h.classList.remove("is-hidden")}function w(){h.classList.add("is-hidden")}function c(){p.classList.remove("is-hidden")}function d(){p.classList.add("is-hidden")}const B=document.querySelector(".form"),M=document.querySelector(".load-more-btn");let i="",n=1,u=0;B.addEventListener("submit",async o=>{if(o.preventDefault(),i=o.currentTarget.elements["search-text"].value.trim(),!i){a.warning({message:"Please enter a search query"});return}n=1,$(),d(),L();try{const e=await y(i,n);u=e.totalHits,e.hits.length===0?a.error({message:"Sorry, no images found!"}):(b(e.hits),u>15||a.info({message:"We're sorry, but you've reached the end of search results."}),c()),o.target.reset()}catch(e){console.log(e),a.error({message:"Something went wrong!"})}finally{w()}});M.addEventListener("click",async()=>{n+=1,d(),L();try{const o=await y(i,n);b(o.hits);const e=document.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}n*15>=u?(d(),a.info({message:"We're sorry, but you've reached the end of search results."})):c()}catch{a.error({message:"Error loading more images!"})}finally{w()}});
//# sourceMappingURL=index.js.map
